### ISSUE TITLE
Токенизация не объединяет сокращения

### ISSUE THREAD

**Issue by kucenko** [natasha/razdel#12]
Заметил что в tokenize нет RULE которое бы объединило сокращение в один терм, это было сделано специально?

Такое правило добавлено в sentenize, что привело к различному формированию токенов

Что бы добавить дополнительное правило необходимо полностью переписать TokenSegmenter, можно дать возможность передавать аргументы как это было сделано для SentSegmenter ?

**Comment by kuk** [comment]
> Заметил что в tokenize нет RULE которое бы объединило сокращение в один терм, это было сделано специально?

Да, так получается выше скор на датасетах, которые приняли за эталонные.

Есть немного в доке https://github.com/natasha/razdel#evaluation:

> What would be the correct way to tokenizer т.е.? One may split in into т.|е., razdel splits into т|.|е|..
> 
> razdel tries to mimic segmentation of these 4 datasets: SynTagRus, OpenCorpora, GICRYA and RNC.

 > Что бы добавить дополнительное правило необходимо полностью переписать TokenSegmenter, можно дать возможность передавать аргументы как это было сделано для SentSegmenter ?

Да, надо конечно сделать `__init__` https://github.com/natasha/razdel/blob/master/razdel/segmenters/tokenize.py#L294 по аналогии с sentenize `__init__` https://github.com/natasha/razdel/blob/master/razdel/segmenters/sentenize.py#L354
