### ISSUE TITLE
В DebugSegmenter \n ломают оформление консоли

### ISSUE THREAD

**Issue by kucenko** [natasha/razdel#13]
Встретил проблему при отладке сегментации

На строке [DebugSegmenter](https://github.com/natasha/razdel/blob/master/razdel/segmenters/base.py#L54) используются `print` которые могут сломать вывод отображения

Предлагаю переписать на `print(repr(split.left), '|', repr(split.delimiter), '|', repr(split.right))`

Таким образом у нас появятся все непечатаемые символы что облегчит разбор отладки

**Comment by kuk** [comment]
Ага, хорошая идея. Только оформить как-то типа` "{split.left!r} | {split.delim!r} | {split.right!r}".format(split=split)`
