### ISSUE TITLE
Не работает ссылка

### ISSUE THREAD

**Issue by Derinhelm** [natasha/razdel#16]
Добрый день!
На главной странице анализатора razdel не работает выделенная ссылка (возвращается 404)
![image](https://user-images.githubusercontent.com/44348320/108199128-9b6cd500-712d-11eb-9030-bdc7e4c85975.png)

**Comment by kuk** [comment]
Спасибо! Поправил, правильная ссылка https://github.com/natasha/naeval/blob/master/scripts/01_segment/main.ipynb
