### ISSUE TITLE
StopIteration Error python3.7

### ISSUE THREAD

**Issue by StanislavPy** [natasha/razdel#5]
Здравствйте, столкнулся со следующей проблемой при использовании на python 3.7. 
Там необходимо немного переписать обращение к генератору, как, например, тут https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-every-time-i-try-to-run-app

Вот так выглядит traceback в данный момент.

```
File "/usr/lib/python3.7/site-packages/razdel/substring.py", line 18, in find_substrings
    for chunk in chunks:
RuntimeError: generator raised StopIteration
```

**Comment by Avenon** [comment]
Тоже столкнулся с данной проблемой под питон версии 3.7

**Comment by kuk** [comment]
Возможно исправлено в https://github.com/natasha/razdel/commit/247493390b8b0dc75872f00d0dab2494cb52ea0b

Попробуйте `pip install razdel==0.5.0 `. Если не поможет напишите пример текста на котором падает
