### ISSUE TITLE
Can razdel load userdict ?

### ISSUE THREAD

**Issue by liutianling** [natasha/razdel#9]

**Comment by kuk** [comment]
What do you mean by userdict?

**Comment by liutianling** [comment]
Thanks for your reply.

**Comment by liutianling** [comment]
> What do you mean by userdict?

Thanks for your reply.
eg: If there is a persom name Jack Stiff in a sentence, I want to split it as a word . That is to say , 'jack stiff' is a token, not 'jack', 'Stiff' two words.
I am sorry for my bad english.

**Comment by kuk** [comment]
Razdel has no built in functionality for that.

You could implement your own rule similar to https://github.com/natasha/razdel/blob/master/razdel/segmenters/tokenize.py#L184 and run tokenizer with custom updated list of rules https://github.com/natasha/razdel/blob/master/razdel/segmenters/tokenize.py#L282 . But this functionality is not currently documented you need to understand internal implementation
